### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#10]
Copied from: https://github.com/CAWSCIT/caws-api/issues/123
Priority: Low.
Impact: Medium
Size: Medium

It would be nice to have a Django admin "dashboard". This would be a new admin view to show some simple data so we can track progress and share numbers in reports. 

Some initial ideas include:
- [ ] Global Django admins only (needs permission checks)
- [ ] How many areas are onboarded vs. How many areas have joined (ie. 33/40 areas have at least one non-suspended meeting). 
- [ ] Potentially duplicate meetings (ie. an area that's made 7 groups for one meeting per day that should be one group with 7 meetings on different days). 
- [ ] Total meetings 

Share additional ideas below 👇

**Comment by KalobTaulien** [comment]
Dashboard is created for superusers. "Stats at a Glance" feature to help with reporting and onboarding progress
