### ISSUE TITLE
Add reference to this repro and how to file issues

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#16]
**Is your feature request related to a problem? Please describe.**
No one knows how to file issues.
**Is this related to the mobile app or meeting entry**
Mobile app
**Describe the solution you'd like**
Add information to about page on how to file issue and link to this repo

**Comment by KalobTaulien** [comment]
Agreed, this is important. 👍 

We could add this information to our README.md file, and link from the app's About Page to here.

**Comment by KalobTaulien** [comment]
Would you say this is addressed in https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/commit/93c720158437841dfb6ecffaf90d3ee941ab002b? @enderv

**Comment by enderv** [comment]
Yep!
