### ISSUE TITLE
Areas cannot change their own data

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#2]
I think it would be beneficial if areas could change the following for themselves:

Region filter key
Email
Phone
Web
Timezone
Idk about language, I am not sure if or how it is used.

**Comment by KalobTaulien** [comment]
Language I don't think we should have as a changeable option. That _could_ have adverse effects in the future when we detect languages for i18n. 

Region as well shouldn't be changeable. But should be displayed.

I've started work on this.

**Comment by KalobTaulien** [comment]
This has been completed. Areas can now manage their own Area data.
