### ISSUE TITLE
A Vision For You Tues OSA - Meeting info running off the page

### ISSUE THREAD

**Issue by TheSoberJewel** [CAWSCIT/ca-meeting-finder-issue-tracker#21]
**Describe the bug**
In the meeting info, the blue bar to connect to Zoom is too long and is running off the page.
Text info for the meeting doesn't appear to be word wrapping on every line and is running off the page.

**To Reproduce**
Tuesday Online Meetings, A Vision For You, 10P ET

**Expected behavior**
Expect all images and text to stay within the boundary for the Meeting Information box.
![A Vision For You image 2024 04 23](https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/assets/167952004/ab4f7885-5f9f-468a-a6bf-14a3b7716b45)

**Screenshots**
Submitted, but accidently attached to **Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android ver 13
 - Browser Google

**Additional context**

**Comment by enderv** [comment]
Might be device specific on pixel 7 pro don't see it
![Screenshot_20240424-200240](https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/assets/3226709/a19beb4d-c498-4899-a6f1-5bd0e0f983a4)
[](url)

**Comment by TheSoberJewel** [comment]
I've noticed this issue on a handful of different Zoom meetings.  Because I don't encounter this issue on every Zoom meeting, I am guessing the issue is caused more by how the user input their info into the system then with anything to do with the app itself.

**Comment by KalobTaulien** [comment]
I setup a Samsung S20 emulator running Android 13 and this is what I got: 

<img width="380" alt="image" src="https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/assets/4743971/fce18499-35d6-4ed4-ba89-425bdf36d792">

The meetings you are seeing @TheSoberJewel are coming in from your default browser. Im curious if this is from your browser version on your phone.

**Comment by KalobTaulien** [comment]
This seems to be an isolated event. I'm going to close, but should the Issue re-appear we can always look into this again.
