### ISSUE TITLE
Force html updates at intervals

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#24]
**Is your feature request related to a problem? Please describe.**
When we update the html there's no way for a user in app to force refresh the meeting list search. Added pulltoRefresh but its iOS only. Need a multi platform solution.

**Is this related to the mobile app or meeting entry**
Mobile app 

**Describe the solution you'd like**
Probably some wrapper around the webview to allow for the list to update  when you go to webview?

**Comment by KalobTaulien** [comment]
Interesting. I had no idea this didn't work on Android. 

What is the typical way for Android users to refresh a page? Do they also pull to refresh?

**Comment by enderv** [comment]
Looks like best way to do this is embed the webview in a  scrollview

**Comment by KalobTaulien** [comment]
This was a lot trickier than expected. But we have a working solution for iOS and Android now.
