### ISSUE TITLE
No loading spinner when meetings are loading 

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#3]
Noticed this when I had a bad signal but was just a white screen until it loaded the html.

Chat on issue: https://github.com/CAWSCIT/ca-mobile-app/issues/31

**Comment by KalobTaulien** [comment]
@enderv This is ready for review in https://github.com/CAWSCIT/ca-mobile-app/pull/48

**Comment by KalobTaulien** [comment]
New code merged in from https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/issues/3

1 second delay to at least _show_ some semblance of a loader in case of slow internet connections.
