### ISSUE TITLE
Back button from MeetingsList Screen doesn't work as expected. 

### ISSUE THREAD

**Issue by KalobTaulien** [CAWSCIT/ca-meeting-finder-issue-tracker#39]
This is a bug report from an Area Chair. 

**Describe the bug**
When in a meeting and I hit the Android back button it goes to the app startup screen(green), doesn't go back one page to the meeting list (as the Back to meetings link does)

**Comment by enderv** [comment]
https://curiosum.com/blog/dedicated-mobile-application-in-react-native-webview-guide has how to set this up

**Comment by KalobTaulien** [comment]
Added to Android from @enderv -- closing as this is now in prod. 🙌
