### ISSUE TITLE
Validate virtual location is a url

### ISSUE THREAD

**Issue by enderv** [CAWSCIT/ca-meeting-finder-issue-tracker#40]
**Is your feature request related to a problem? Please describe.**
tsml expects conference url to be valid urls but in the admin API users can enter any text.

**Is this related to the mobile app or meeting entry**
Meeting entry

**Describe the solution you'd like**
We should validate on input and possibly validate on GET and remove invalid entries

**Additional context**
if invalid url is entered tsml-ui just shows typeError: cannot read properties of undefined

**Comment by KalobTaulien** [comment]
URLs are validated upon saving now https://github.com/CAWSCIT/caws-api/commit/a21e77a067eff7a94ff1be027a2f2d94ac2bd5c1 

I'll work on updating TSML to check if incoming conference URL's are valid URLs.

**Comment by KalobTaulien** [comment]
PR opened to validate TSML Plugin URLs https://github.com/CAWSCIT/caws-api/pull/141
