### ISSUE TITLE
Add to Calendar not working (iOS and Android) 

### ISSUE THREAD

**Issue by KalobTaulien** [CAWSCIT/ca-meeting-finder-issue-tracker#45]
**Describe the bug**
"Add to Calendar" feature in TSML does not work. 

**To Reproduce**
1. Open the Meetings view in the app (ios or android, both have this bug)
2. Click on any meeting 
3. Click "Add to Calendar"
4. See that nothing happens

**Expected behavior**
It should ask to add a calendar event in your calendar app (I think). At least thats what it does in the brwoser. 

**Screenshots**
![image](https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/assets/4743971/6c4c76a5-fb9b-40cb-8ec4-84116ba42f99)

**Smartphone**
 - Device: iPhone 15, PIxel 7

**Additional context**
Simulator/Android Studio _and_ on an actual phone seem to do this.

**Comment by enderv** [comment]
https://github.com/react-native-webview/react-native-webview/issues/2858 looks similar to this. TSML is generating a ics blob on the fly and a fake link

**Comment by enderv** [comment]
https://github.com/react-native-webview/react-native-webview/pull/3022 sad

**Comment by KalobTaulien** [comment]
Closing this Issue because we have this feature disabled for the time being.
