### ISSUE TITLE
iPhone app: the sobriety date picker closes if the date changes and so you change part of the date (like the year) and it saves the date right away.

### ISSUE THREAD

**Issue by tiptop96** [CAWSCIT/ca-meeting-finder-issue-tracker#46]
To reproduce just try to set a date on the date picker, it should be obvious, if it isn't then ping me and I will try to do a screen recording.

**Comment by KalobTaulien** [comment]
I have an open PR for this. Should be a quick one to review and get added into the app soon.

**Comment by KalobTaulien** [comment]
Bug(s) patched. Will be seen in the next TestFlight release. Android didn't have this problem, only iOS.
