### ISSUE TITLE
Set distance unit based on users locale

### ISSUE THREAD

**Issue by tiptop96** [CAWSCIT/ca-meeting-finder-issue-tracker#47]
Maybe set the config prop referenced here https://github.com/code4recovery/tsml-ui?tab=readme-ov-file#use-kilometers using something like `isMetric` from https://docs.expo.dev/versions/latest/sdk/localization/#localization

**Comment by KalobTaulien** [comment]
Fixed in https://github.com/CAWSCIT/ca-mobile-app/pull/62
