### ISSUE TITLE
"null" indicated on some meeting.

### ISSUE THREAD

**Issue by Totoquebec** [CAWSCIT/ca-meeting-finder-issue-tracker#56]
**Describe the bug**
In the app, If I choose Central UK, The have 'null" text in the address.

**To Reproduce**
1. Go to the Apps
2. Click on choose where
3. Scroll down to Central UK
4. Scoll the list and you will see "null" in some address

**Expected behavior**
The record for the meeting should be reject or at least the 'null' text should be replace by space.

**Screenshots**
Screen shot at the bottom

**Desktop (please complete the following information):**
Appear on destop

**Smartphone (please complete the following information):**
Appear on Android

![Screenshot_20240821_161010_CA Meeting Finder](https://github.com/user-attachments/assets/5dc3fa73-cda6-4d1f-97fd-52f88e9f6488)

**Comment by enderv** [comment]
Thanks for the report. Took a look and all the ones I saw actually have "some address string null" for the location address in the database.  Will need some more digging to see if this is something that's getting auto filled by something

**Comment by KalobTaulien** [comment]
This seemed to be a bug with TSML UI that has been patched. Closing for now, but if this appears again please re-open this ticket.
