### ISSUE TITLE
iOS Location Service

### ISSUE THREAD

**Issue by Hungs0l0** [CAWSCIT/ca-meeting-finder-issue-tracker#57]
**Describe the bug**
Location services does not appear to work on iOS app.  

**To Reproduce**
Install iOS app
Open app
iOS asks to use location
No matter choice, app opens will worldwide meetings as default, not closest to current location
This happens even when turning location services for app to always use.

**Expected behavior**
Meetings closest to current location appear first in list when opening app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 17.4.1

**Comment by enderv** [comment]
`No matter choice, app opens will worldwide meetings as default, not closest to current location` this is the current default behavior. Are you able to search by location "near me" if you select that option?

**Comment by Hungs0l0** [comment]
Correct, able to filter by Near Me, but that default is not saved.  So probably a feature request to open to last used filter.

**Comment by enderv** [comment]
@KalobTaulien fyi on this one, think that change is still queued up but i've last track

**Comment by KalobTaulien** [comment]
Hi @Hungs0l0 and @enderv -- That feature is queued up and ready in the next release. 🙌

**Comment by KalobTaulien** [comment]
This has been released on iOS and Android 🙌
